[templates]

[bashrc]
paths = [
    "~/.bashrc",
]

[config-hypr]
paths = [
    "~/.config/hypr",
]
post_deploy = "notify-send \"Reloading Hyprland\" && hyprctl reload"

[config-quickshell]
paths = [
    "~/.config/quickshell",
]
post_deploy = "notify-send \"Reloading Quickshell\""

[config-illogical-impulse]
paths = [
    "~/.config/illogical-impulse",
]

[config-fish]
paths = [
    "~/.config/fish",
]

[config-kitty]
paths = [
    "~/.config/kitty",
]